//
//  SongDetailInteractor.swift
//  CodingChallenge
//
//  Created by Edgar Barocio on 6/22/19.
//  Copyright (c) 2019 Edgar Barocio. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SongDetailBusinessLogic {
  func doSomething(request: SongDetail.Something.Request)
}

protocol SongDetailDataStore {
  //var name: String { get set }
}

class SongDetailInteractor: SongDetailBusinessLogic, SongDetailDataStore {
  var presenter: SongDetailPresentationLogic?
  var worker: SongDetailWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: SongDetail.Something.Request) {
    worker = SongDetailWorker()
    worker?.doSomeWork()
    
    let response = SongDetail.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
