//
//  SongDetailPresenter.swift
//  CodingChallenge
//
//  Created by Edgar Barocio on 6/22/19.
//  Copyright (c) 2019 Edgar Barocio. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SongDetailPresentationLogic {
    func presentSomething(response: SongDetail.Something.Response)
}

class SongDetailPresenter: SongDetailPresentationLogic {
    weak var viewController: SongDetailDisplayLogic?
    
    // MARK: Do something
    
    func presentSomething(response: SongDetail.Something.Response) {
        let viewModel = SongDetail.Something.ViewModel()
        viewController?.displaySomething(viewModel: viewModel)
    }
}
