//
//  SongDetailViewController.swift
//  CodingChallenge
//
//  Created by Edgar Barocio on 6/22/19.
//  Copyright (c) 2019 Edgar Barocio. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class SongDetailViewController: UIViewController {
    @IBOutlet var albumArt: UIImageView!
    @IBOutlet var trackName: UILabel!
    @IBOutlet var trackArtist: UILabel!
    
    var albumURL = ""
    var track = ""
    var artist = ""

    // MARK: View lifecycle
    
    override func viewDidLoad() {
        super.viewDidLoad()
        let url = URL(string: albumURL )
        
        DispatchQueue.global().async {
            let data = try? Data(contentsOf: url!)
            DispatchQueue.main.async {
                self.albumArt.image = UIImage(data: data!)
            }
        }
        self.trackArtist.text = track
        self.trackName.text = artist
    }
}
