//
//  MusicSearchPresenter.swift
//  CodingChallenge
//
//  Created by Edgar Barocio on 6/22/19.
//  Copyright (c) 2019 Edgar Barocio. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MusicSearchPresentationLogic {
  func presentSomething(response: MusicSearch.Something.Response)
}

class MusicSearchPresenter: MusicSearchPresentationLogic {
  weak var viewController: MusicSearchDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: MusicSearch.Something.Response) {
    let viewModel = MusicSearch.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
