//
//  MusicSearchInteractor.swift
//  CodingChallenge
//
//  Created by Edgar Barocio on 6/22/19.
//  Copyright (c) 2019 Edgar Barocio. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MusicSearchBusinessLogic {
    func performSearch(request: MusicSearch.Search.Request)
}

protocol MusicSearchDataStore {
    //var name: String { get set }
}

class MusicSearchInteractor: MusicSearchBusinessLogic, MusicSearchDataStore {
    var presenter: MusicSearchPresentationLogic?
    var worker: MusicSearchWorker?
    
    // MARK: Do something
    
    func performSearch(request: MusicSearch.Search.Request) {
        worker = MusicSearchWorker()
        worker?.doSomeWork()
        
        let response = MusicSearch.Search.Response()
        presenter?.presentSomething(response: response)
    }
    
    
    
}
