//
//  MusicSearchInteractor.swift
//  CodingChallenge
//
//  Created by Edgar Barocio on 6/22/19.
//  Copyright (c) 2019 Edgar Barocio. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MusicSearchBusinessLogic {
    
    func performSearch(request: MusicSearch.Search.Request)
}

protocol MusicSearchDataStore {
    var songs: [SongResponse]? { get }
}

class MusicSearchInteractor: MusicSearchBusinessLogic, MusicSearchDataStore {
    var presenter: MusicSearchPresentationLogic?
    var searchWorker: MusicSearchWorker?
    var songs: [SongResponse]?
    
    // MARK: Fetch songs
    
    func performSearch(request: MusicSearch.Search.Request) {
        searchWorker = MusicSearchWorker()
        searchWorker?.performSearch(searchTerm: request.searchTerm) { (songs) -> Void in
            self.songs = songs
            let response = MusicSearch.Search.Response(searchResult: songs)
            self.presenter?.presentSongs(response: response)
        }
    }
}
