//
//  MusicSearchInteractor.swift
//  CodingChallenge
//
//  Created by Edgar Barocio on 6/22/19.
//  Copyright (c) 2019 Edgar Barocio. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MusicSearchBusinessLogic {
  func doSomething(request: MusicSearch.Something.Request)
}

protocol MusicSearchDataStore {
  //var name: String { get set }
}

class MusicSearchInteractor: MusicSearchBusinessLogic, MusicSearchDataStore {
  var presenter: MusicSearchPresentationLogic?
  var worker: MusicSearchWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: MusicSearch.Something.Request) {
    worker = MusicSearchWorker()
    worker?.doSomeWork()
    
    let response = MusicSearch.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
