//
//  MusicSearchViewController.swift
//  CodingChallenge
//
//  Created by Edgar Barocio on 6/22/19.
//  Copyright (c) 2019 Edgar Barocio. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MusicSearchDisplayLogic: class {
  func displaySomething(viewModel: MusicSearch.Something.ViewModel)
}

class MusicSearchViewController: UIViewController, MusicSearchDisplayLogic {
  var interactor: MusicSearchBusinessLogic?
  var router: (NSObjectProtocol & MusicSearchRoutingLogic & MusicSearchDataPassing)?

  // MARK: Object lifecycle
  
  override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
    super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
    setup()
  }
  
  required init?(coder aDecoder: NSCoder) {
    super.init(coder: aDecoder)
    setup()
  }
  
  // MARK: Setup
  
  private func setup() {
    let viewController = self
    let interactor = MusicSearchInteractor()
    let presenter = MusicSearchPresenter()
    let router = MusicSearchRouter()
    viewController.interactor = interactor
    viewController.router = router
    interactor.presenter = presenter
    presenter.viewController = viewController
    router.viewController = viewController
    router.dataStore = interactor
  }
  
  // MARK: Routing
  
  override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
    if let scene = segue.identifier {
      let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
      if let router = router, router.responds(to: selector) {
        router.perform(selector, with: segue)
      }
    }
  }
  
  // MARK: View lifecycle
  
  override func viewDidLoad() {
    super.viewDidLoad()
    doSomething()
  }
  
  // MARK: Do something
  
  //@IBOutlet weak var nameTextField: UITextField!
  
  func doSomething() {
    let request = MusicSearch.Something.Request()
    interactor?.doSomething(request: request)
  }
  
  func displaySomething(viewModel: MusicSearch.Something.ViewModel) {
    //nameTextField.text = viewModel.name
  }
}


// MARK: Text Displayed on Search

