//
//  MusicSearchViewController.swift
//  CodingChallenge
//
//  Created by Edgar Barocio on 6/22/19.
//  Copyright (c) 2019 Edgar Barocio. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit


// Enum to display seach status
private enum SearchDisplayResults: String {
    case firstMessage = "Enter Search Term"
    case loadingMessage = "Searching"
    case noResults = "No Results Found"
}

private enum SegueList: String {
    case ShowSongSegue = "ShowSong"
}

protocol MusicSearchDisplayLogic: class {
    func displayResults(viewModel: MusicSearch.Search.ViewModel)
}

class MusicSearchViewController: UIViewController, MusicSearchDisplayLogic, UITextFieldDelegate, UICollectionViewDelegate {
    
    @IBOutlet var searchTextField: UITextField!
    @IBOutlet var cancelButton: UIButton!
    @IBOutlet var searchStatusLabel: UILabel!
    @IBOutlet var resultsCollection: UICollectionView!
    
    let resultsDataSource = SearchDataSource()
    
    var interactor: MusicSearchBusinessLogic?
    var router: (NSObjectProtocol & MusicSearchRoutingLogic & MusicSearchDataPassing)?
    
    // MARK: Object lifecycle
    
    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        setup()
    }
    
    required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
        setup()
    }
    
    // MARK: Setup
    
    private func setup() {
        let viewController = self
        let interactor = MusicSearchInteractor()
        let presenter = MusicSearchPresenter()
        let router = MusicSearchRouter()
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        presenter.viewController = viewController
        router.viewController = viewController
        router.dataStore = interactor
    }
    
    // MARK: Routing
    
    override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
        if segue.identifier == "ShowSong" {
            let data = sender as? SongResponse
            let vc = segue.destination as! SongDetailViewController
            vc.albumURL = data?.artworkUrl100 ?? ""
            vc.artist = data?.artistName ?? ""
            vc.track = data?.trackName ?? ""
        }
    }
    
    // MARK: View lifecycle
    
    override func viewDidLoad() {
        super.viewDidLoad()
        
        resultsCollection?.dataSource = resultsDataSource
        resultsCollection?.delegate = self
        resultsCollection?.register(UINib.init(nibName: "SearchResultCell", bundle: nil), forCellWithReuseIdentifier: SearchResultCell.identifier)
        resultsCollection?.isHidden = true
        cancelButton?.isEnabled = false
        searchStatusLabel?.text = SearchDisplayResults.firstMessage.rawValue
    }
    
    // MARK: Search Function
    func performSearch() {
        if let searchText = searchTextField.text?.trimmingCharacters(in: .whitespaces),
            !searchText.isEmpty {
            let request = MusicSearch.Search.Request(searchTerm: searchTextField?.text ?? "")
            searchStatusLabel?.text = SearchDisplayResults.loadingMessage.rawValue
            UIApplication.shared.isNetworkActivityIndicatorVisible = true
            interactor?.performSearch(request: request)
        }
        
    }
    
    func displayResults(viewModel: MusicSearch.Search.ViewModel) {
        UIApplication.shared.isNetworkActivityIndicatorVisible = false
        
        guard let result = viewModel.searchResult else {
            searchStatusLabel?.text = SearchDisplayResults.noResults.rawValue
            return
        }
        
        searchStatusLabel?.isHidden = true
        resultsCollection?.isHidden = false
        resultsDataSource.results = result
        resultsCollection?.reloadData()
    }
    
    // MARK: Text Delegate Functions
    func textFieldDidBeginEditing(_ textField: UITextField) {
        cancelButton?.isEnabled = true
    }
    
    // MARK: Protocol implementation
    func textFieldShouldReturn(_ textField: UITextField) -> Bool {
        textField.resignFirstResponder()
        performSearch()
        
        return true
    }
    
    // MARK: Collection View Delegate
    func collectionView(_ collectionView: UICollectionView, didSelectItemAt indexPath: IndexPath) {
        //Navigate to detail
        performSegue(withIdentifier: SegueList.ShowSongSegue.rawValue, sender: resultsDataSource.results[indexPath.row])
    }
    
    // MARK: Button Acton
    @IBAction func cancelPressed(_ sender: Any) {
        searchTextField?.resignFirstResponder()
    }
}
