//
//  MusicSearchWorker.swift
//  CodingChallenge
//
//  Created by Edgar Barocio on 6/22/19.
//  Copyright (c) 2019 Edgar Barocio. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class MusicSearchWorker {
    
    var songResults:[SongResponse] = []
    let queryService = QueryService()
    
    func performSearch(searchTerm:String, completionHandler: @escaping ([SongResponse]) -> Void) {
        queryService.getSearchResults(searchTerm: searchTerm) { results , errorMessage in
            if let results = results {
                self.songResults = results
                DispatchQueue.main.async {
                    completionHandler(self.songResults)
                }
            } else {
                DispatchQueue.main.async {
                    completionHandler([])
                }
            }
            
            if !errorMessage.isEmpty {
                print("Search error: " + errorMessage)
            }
        }
    }
}
